DROP TABLE IF EXISTS NAVE ;
CREATE TABLE IF NOT EXISTS NAVE(
    idnave BIGINT NOT NULL PRIMARY KEY auto_increment,
    nombre VARCHAR (30) NOT NULL,
    motores INTEGER NOT NULL);
DROP TABLE IF EXISTS PERSONAJE ;
CREATE TABLE IF NOT EXISTS PERSONAJE(
    codigo BIGINT NOT NULL PRIMARY KEY auto_increment,
    nombre VARCHAR (50) NOT NULL,
    descripcion VARCHAR (100) NOT NULL,
    tipo VARCHAR (30) NOT NULL);
DROP TABLE IF EXISTS PILOTA ;
CREATE TABLE IF NOT EXISTS PILOTA(
    codpersonaje BIGINT NOT NULL,
    condnave VARCHAR (30) NOT NULL,
    fecha DATE NOT NULL,
    navesabatidas INTEGER NOT NULL,
    FOREIGN KEY(codpersonaje) REFERENCES PERSONAJE (codigo) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(condnave) REFERENCES NAVE (idnave) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (codpersonaje,condnave,fecha));

